-- MySQL Script generated by MySQL Workbench
-- Wed May 24 10:17:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`usuario` (
  `idusr` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusr`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`livro` (
  `idlivro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `pag` INT NOT NULL,
  `autor` VARCHAR(255) NOT NULL,
  `editora` VARCHAR(255) NOT NULL,
  `ano` DATE NOT NULL,
  `sinopse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idlivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`carrinho` (
  `idcarrinho` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  `usuario_idusr` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  CONSTRAINT `fk_carrinho_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `library`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_usuario1`
    FOREIGN KEY (`usuario_idusr`)
    REFERENCES `library`.`usuario` (`idusr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `library`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusr` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  `carrinho_idcarrinho` INT NULL,
  PRIMARY KEY (`idcompra`),
  CONSTRAINT `fk_compra_usuario`
    FOREIGN KEY (`usuario_idusr`)
    REFERENCES `library`.`usuario` (`idusr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `library`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_carrinho1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `library`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `library`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `livro_idlivro` INT NOT NULL,
  PRIMARY KEY (`idgenero`),
  CONSTRAINT `fk_genero_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `library`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `library`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `identficacao` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;
